name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run --if-present type-check
      - run: pnpm run --if-present lint
      - run: pnpm run --if-present prettier:check
      - run: pnpm test
      - run: pnpm run --if-presetn build
